config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
  devise_for :users 
  
  resources :app_posts do
    resource :cover_image, only: [:destroy], module: :app_posts
    member do
      patch :publish
    end
  end
  # get "/app_posts", to: "app_posts#index", as: :app_posts
  # get "/app_posts/new", to: "app_posts#new", as: :new_app_post
  # get "/app_posts/:id", to: "app_posts#show", as: :app_post
  # patch "/app_posts/:id", to: "app_posts#update"
  # delete "/app_posts/:id", to: "app_posts#destroy"
  # get "/app_posts/:id/edit", to: "app_posts#edit", as: :edit_app_post
  # post "/app_posts",  to: "app_posts#create"

  
  # Defines the root path route ("/")
  root "app_posts#index"
  end

app/models/app_post.rb
class AppPost < ApplicationRecord
    attr_accessor :body
    has_many :comments
    has_one_attached :cover_image
    has_rich_text :content
    has_many :dummies

    validates :title, presence: true
    validates :content, presence: true

scope :sorted, ->{ order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
scope :draft, -> { where(published_at: nil) }
scope :published, -> { where("published_at <= ?", Time.current) }
scope :scheduled, -> { where("published_at > ?", Time.current) }

def draft?
    published_at.nil?
end

def published?
    published_at?  && published_at <= Time.current
end

def schedule?
    published_at? && published_at > Time.current
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/dummy.rb
class Dummy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 attr_accessor :subscription_status
  
  after_commit :create_stripe_customer, on: :create

  def subscribe?
    subscription_status == 'active'
  end

  def create_stripe_customer
    CreateStripeCustomerJob.perform_later(id)
  end
end

app/controllers/app_posts/cover_images_controller.rb
class AppPosts::CoverImagesController < ApplicationController
    include ActionView::RecordIdentifier
    
 before_action :authenticate_user!
 before_action :set_app_post

 def destroy
    @app_post.cover_image.purge_later

    respond_to do |format|
    format.html { redirect_to edit_app_post_path(@app_post) }
    format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@app_post, :cover_image)) }
 end
end

#  private

 def set_app_post
    @app_post = AppPost.find(params[:app_post_id])
 end
end

app/controllers/app_posts_controller.rb
class AppPostsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show]
    before_action :set_app_post, except: [:index, :new, :create]

    def index
        @app_posts = user_signed_in? ? AppPost.sorted : AppPost.published.sorted
        @pagy, @app_posts = pagy(@app_posts)
         rescue Pagy::OverflowError
        redirect_to root_path(page: 1)
    end  
    
    
    def show
        # @comments = @app_post.comments.includes(:replies)
        # @app_post = AppPost.find(params[:id])
        # rescue ActiveRecords::RecordNotFound
        # redirect_to root_path
    end

    def new
        @app_post = AppPost.new
    end

    def create
        @app_post = AppPost.new(app_post_params)
        if @app_post.save
            redirect_to @app_post
        else
        render :new, status: :unprocessable_entity
    end
end

def edit
    # @app_post = AppPost.find(params[:id])
end

def update
    # @app_post = AppPost.find(params[:id])
    if @app_post.update(app_post_params)
        redirect_to @app_post
    else
        render :edit, status: :unprocessable_entity
   end
end

def destroy
    # @app_post = AppPost.find(params[:id])
    @app_post.destroy
    respond_to do |format|
    format.html { redirect_to root_path }
        format.js
      end
end

def publish
    @app_post = AppPost.find(params[:id])
    if @app_post.update(published_at: Time.now)
    respond_to do |format|
        format.js
    end
    else
        render :edit, status: :unprocessable_entity
    end
end


private

   def app_post_params
         params.require(:app_post).permit(:title, :content, :cover_image, :published_at)
    end


def set_app_post
    @app_post = user_signed_in? ? AppPost.find(params[:id]) : AppPost.published.find(params[:id])
rescue ActiveRecord::RecordNotFound
    redirect_to root_path
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/app_posts/_form.html.erb
<%= form_with model: @app_post do |form| %>
<% if form.object.errors.any? %>
<div>
    <% form.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>
<% end %>

</div>
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div>
  <%= form.label :cover_image %>
  <% if app_post.cover_image.present? %>
  <div id="<%= dom_id(app_post, :cover_image) %>">
  <%= image_tag app_post.cover_image, class: "w-1/3" %>
  <%= link_to "Remove cover image", app_post_cover_image_path(app_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure? Any other changes you make will be lost." } %>
</div>
  <% end %>
  <%= form.file_field :cover_image %>
</div>

<div>
<%= form.label :content %>
<%= form.rich_text_area :content %>
</div>

<div>
<%= form.label :published_at %>
<%= form.datetime_select :published_at, include_blank: true %>
</div>

<%= form.button %>
<% end %>

app/views/app_posts/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
 <style>
      body {
        background-color: lightyellow; 
      }
    </style>
  </head>
  <body class="prose mx-auto">
<h1>Edit App post</h1>
<%= render partial: "form", locals: { app_post: @app_post } %>
<%= button_to "Delete", app_post_path(@app_post), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this post?" }, class: "delete-button", id: "delete-post-button", remote: true %>
<%= button_to  app_posts_path, method: :get, class: "back-button", remote: true do %>
  <span class="fas fa-spinner fa-spin" style="display: none;"></span>
      Back
    <% end %>
</body>
</html>

<script>
  $(document).ready(function() {
    $('#delete-post-button').click(function() {
      $.ajax({
        url: '<%= app_post_path(@app_post) %>',
        type: 'DELETE',
        dataType: 'script',
        headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') },
        success: function(response) {
          alert("successfull")
          windows.location.href = windows.location.href;
        },
        error: function(xhr, textStatus, errorThrown) {
          alert('Error during deletion.');
        }
      });
    });
  });
</script>

<script>
  $(document).on('click', '.back-button', function() {
    var $button = $(this);
    if (!$button.hasClass('disabled')) {
      $button.find('.fa-spinner').show();
      $button.addClass('animate-back-button');
      $.ajax({
        url: '<%= app_posts_path %>',
        type: 'GET',
        dataType: 'script',
        success: function(response) {   
        },
        error: function(xhr, textStatus, errorThrown) {
        },
        complete: function() {
          setTimeout(function() {
            $button.removeClass('animate-back-button');
            $button.removeClass('disabled');
            $button.find('.fa-spinner').hide();
          }, 3000); 
        }
      });
    }
  });
</script>

app/views/app_posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  <div>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
</div>
 <style>
      body {
        background-color: #C9FFE5; 
      }
    </style>
  </head>
  <body class="prose mx-auto">
<h1> My App </h1>

<% @app_posts.each do |app_post| %>
<div>
<%= image_tag app_post.cover_image if app_post.cover_image.present? %>

<h2><%= link_to app_post.title, app_post  %></h2>
<% if app_post.draft? %>
    <div class="p-2 rounded bg-red-100 text-gray-900">Draft</div>
    <% elsif app_post.schedule? %>
    <div class="p-2 rounded bg-blue-100 text-blue-900">Schedule</div>
    <% else app_post.published? %>
    <div class="p-2 rounded bg-blue-100 text-blue-900">Published</div>
<% end %>
<%= app_post.content %>
</div>
<% end %>

<div class="my-16">

<% if @pagy.count > @pagy.items %>
<div class="my-16">
<%== pagy_nav(@pagy) %>
</div>
<% end %>

</body>
</html>

app/views/app_posts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
 <style>
      body {
        background-color: pink; 
      }
    </style>
  </head>
  <body class="prose mx-auto">
    <h1>New App Post</h1>
    <%= render partial: "form", locals: { app_post: @app_post } %>
  </body>
</html>

app/views/app_posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      background-color: lightblue;
    }
  </style>
</head>
<body class="prose mx-auto">
  <h1>Show</h1>
  <% if user_signed_in? %>
    <%= button_to edit_app_post_path(@app_post), method: :get, class: "edit-button", remote: true do %>
      <span class="fas fa-spinner fa-spin" style="display: none;"></span>
      Edit
    <% end %>
  <% end %>
  <% if @app_post.cover_image.present? %>
    <%= image_tag @app_post.cover_image %>
  <% end %>
  <h2><%= @app_post.title %></h2>
  <%= @app_post.content %>
  
  <p>
    <strong>Published At:</strong>
    <span id="published-at"><%= @app_post.published_at %></span>
  </p>

  <button id="publish-button" class="publish-button">
  <strong> Publish</strong>
  </button>

  <%= button_to  app_posts_path, method: :get, class: "back-button", remote: true do %>
  <span class="fas fa-spinner fa-spin" style="display: none;"></span>
  <strong> Back </strong>
  <% end %>

</body>
</html>


<script>
  $(document).on('click', '.edit-button', function() {
    var $button = $(this);
    if (!$button.hasClass('disabled')) {
      $button.find('.fa-spinner').show();
      $button.addClass('animate-edit-button');
      $.ajax({
        url: '<%= edit_app_post_path(@app_post) %>',
        type: 'GET',
        dataType: 'script',
        success: function(response) {   
        },
        error: function(xhr, textStatus, errorThrown) {
        },
        complete: function() {
          setTimeout(function() {
            $button.removeClass('animate-edit-button');
            $button.removeClass('disabled');
            $button.find('.fa-spinner').hide();
          }, 100); 
        }
      });
    }
  });
</script>

<script>
  $(document).on('click', '.back-button', function() {
    var $button = $(this);
    if (!$button.hasClass('disabled')) {
      $button.find('.fa-spinner').show();
      $button.addClass('animate-back-button');
      $.ajax({
        url: '<%= app_posts_path %>',
        type: 'GET',
        dataType: 'script',
        success: function(response) {   
        },
        error: function(xhr, textStatus, errorThrown) {
        },
        complete: function() {
          setTimeout(function() {
            $button.removeClass('animate-back-button');
            $button.removeClass('disabled');
            $button.find('.fa-spinner').hide();
          }, 100); 
        }
      });
    }
  });
</script>

<script>
  $(document).ready(function () {
    $('#publish-button').click(function () {
      $.ajax({
        type: 'patch', 
        url: '<%= publish_app_post_path(@app_post) %>', 
        data: {
          app_post: { published_at: new Date().toISOString() }, 
          authenticity_token: '<%= form_authenticity_token.to_s %>'
        },
        success: function (data) {
          $('#published-at').text('Published At: ' + new Date().toLocaleString());
          if (data.published) {
         $('#publish-button').text('Published');          }
        },
      });
    });
  });
</script>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all",  "data-turbo-track": "reload" %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body class="prose mx-auto"> 
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


<div>
  <% if user_signed_in? %>
  <%= link_to "New app post", new_app_post_path %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete, id: "logout-button", class: "logout-button" %>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>